### ISSUE TITLE
JOINT ISSUE IMANI AND VAL USER AUTH JWT react router

### ISSUE THREAD

**Issue by vdigregorio** [vdigregorio/ECEpeasy#2]
Trying to pass the user id into database through middleware on api call on function, no luck so far.

What we tried: we researched, have been stuck for hours, and have tried several different things like passing through state, playing around with the code and asking our peers!

PLEASE HELP! 

@imaninyasia
@gittheking @jasonseminara @rapala61 @trevorpreston @irwintsay

**Comment by vdigregorio** [comment]
@jasonseminara
help plzz

**Comment by rapala61** [comment]
Hi Valeria, can you close this issue, please? Thanks!
